## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Hypothesis

We hypothesize that the relationship between San Diego Trolley ridership and nearby crime rates over time will be weak or mixed, rather than uniformly positive or negative. This is because we expect that any observed differences in crime patterns will be driven largely by preexisting neighborhood socioeconomic conditions, rather than the transit use itself. This aligns with prior research suggesting public transit is often blamed for crime patterns that reflect broader structural inequities rather than transit use.

Null Hypothesis: Changes in San Diego Trolley ridership have no association with nearby crime rates over time.

Alternative Hypothesis: Any association between trolley ridership and crime varies across neighborhoods and is more strongly related to socioeconomic context than to ridership levels alone.

## Data

### Data overview

- Dataset #1
  - Dataset Name: Transit Stops Data
  - Link to the dataset:
     csv file: https://raw.githubusercontent.com/COGS108/Group022_WI26/refs/heads/master/data/00-raw/transit_stops_datasd.csv
  found on: https://data.sandiego.gov/datasets/transit-stops/ 
  - Number of observations: 6220
  - Number of variables: 14
  - variables most relevant to this project: 
  The most relevant variables in this dataset are stop_name, stop_lat, and stop_lon. These provide the geographic location of each transit stop. These latitude and longitude coordinates allow us to map stop locations and consider spatial patterns across San Diego. The stop_id and stop_code uniquely identify each transit stop and might be helpful for potential merging with other transit-related datasets.
  - shortcomings of this dataset:
    This data set has strictly static information and does not include ridership data, service frequency, route information, demographic/socioeconomic context, or temporal variables. Because of this, it cannot directly measure usage patterns or equity without being combined with additional datasets.


- Dataset #2 (if you have more than one!)
  - same as above
- etc

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [17]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [18]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data 

# this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/COGS108/Group022_WI26/refs/heads/master/data/00-raw/transit_stops_datasd.csv', 'filename':'transit_stops_datasd.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading transit_stops_datasd.csv:   0%|          | 0.00/287k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  2.86it/s]

Successfully downloaded: transit_stops_datasd.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  5.16it/s]

Successfully downloaded: bad-drivers.csv

In [19]:
import pandas as pd

transit_df = pd.read_csv("data/00-raw/transit_stops_datasd.csv")

transit_df.shape

(6220, 14)

### Transit Stops Data

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [56]:
# Drop any rows or columns are completely null
clean_transit_df = transit_df.dropna(how='all', axis=0)
clean_transit_df = transit_df.dropna(how='all', axis=1)

In [57]:
# Shape of dataset
print(f'Columns in dataset: {clean_transit_df.shape[1]}\nRows in dataset: {clean_transit_df.shape[0]}')

Columns in dataset: 14
Rows in dataset: 6220

In [58]:
# Seeing what percent of columns have null values
empty_columns = list()
for col in clean_transit_df.columns:
    if ((clean_transit_df.shape[0] - clean_transit_df[col].count()) / clean_transit_df.shape[0]) * 100 > 5:
        empty_columns.append(col)
        
    print(f'{col}: {round(((clean_transit_df.shape[0] - clean_transit_df[col].count()) / clean_transit_df.shape[0]) * 100, 2)}% null\n----------------------')

objectid: 0.0% null
----------------------
stop_uid: 0.0% null
----------------------
stop_id: 0.0% null
----------------------
stop_code: 1.85% null
----------------------
stop_name: 0.0% null
----------------------
stop_lat: 0.0% null
----------------------
stop_lon: 0.0% null
----------------------
stop_agncy: 0.0% null
----------------------
wheelchair: 29.5% null
----------------------
intersec: 5.31% null
----------------------
stop_place: 72.86% null
----------------------
parent_sta: 95.08% null
----------------------
lat: 0.0% null
----------------------
lng: 0.0% null
----------------------

In [59]:
# Focusing on columns which have null values over 5% (I will call them empty_columns)

for col in empty_columns:
    print(f'Different kinds of values in {col}:')
    print(clean_transit_df[col].value_counts())
    print('-----------------')

Different kinds of values in wheelchair:
wheelchair
1.0    3174
0.0     741
2.0     470
Name: count, dtype: int64
-----------------
Different kinds of values in intersec:
intersec
F-W/B             815
F-E/B             798
F-N/B             759
F-S/B             727
N-W/B             522
N-E/B             490
N-S/B             450
N-N/B             434
M-Street-E/B      214
M-Street-W/B      177
M-TC-Bus          167
M-Street-S/B      132
M-Street-N/B      119
M-Special_Loc      48
M-TC-Train-N/B     18
M-TC-Train-S/B     14
M-TC-Train-E/B      4
M-TC-Train-W/B      2
Name: count, dtype: int64
-----------------
Different kinds of values in stop_place:
stop_place
esctc     12
euctro    10
mirsta    10
iritro    10
ecajtc    10
          ..
lvgenW     1
lvgenE     1
lvgenS     1
kearny     1
pacpac     1
Name: count, Length: 1029, dtype: int64
-----------------
Different kinds of values in parent_sta:
parent_sta
esctc     12
iritro    10
ecajtc    10
euctro    10
fasvtc    10
          ..
peptc      1
genljN     1
amptro     1
sanS       1
i15els     1
Name: count, Length: 110, dtype: int64
-----------------

In [60]:
# The columns look to either be irrelevant to our project or too imcomplete to evaluate
# So lets drop them

print('Dropping empty_columns')
clean_transit_df = clean_transit_df.drop(columns=empty_columns)
clean_transit_df

Dropping empty_columns

,objectid,stop_uid,stop_id,stop_code,stop_name,stop_lat,stop_lon,stop_agncy,lat,lng
0,1,MTS_11tbro,11tbro,NaN,11th Ave & Broadway,32.716268,-117.154649,MTS,32.716263,-117.154637
1,2,MTS_12tS,12tS,NaN,12th & Imperial Station,32.706002,-117.153378,MTS,32.705997,-117.153366
2,3,MTS_imtS,imtS,NaN,12th & Imperial Station Bayside,32.705229,-117.154318,MTS,32.705224,-117.154306
3,4,MTS_imp12,imp12,NaN,12th & Imperial Transit Center,32.705685,-117.152875,MTS,32.705680,-117.152863
4,5,MTS_24tS,24tS,NaN,24th Street Station,32.661854,-117.108017,MTS,32.661849,-117.108005
...,...,...,...,...,...,...,...,...,...,...
6215,6216,NCTD_pcrtc,pcrtc,NaN,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD,33.178271,-117.336513
6216,6217,NCTD_slrtc,slrtc,NaN,San Luis Rey Transit Center,33.254410,-117.298129,NCTD,33.254405,-117.298117
6217,6218,NCTD_solsta,solsta,NaN,Solana Beach Station,32.992937,-117.271067,NCTD,32.992932,-117.271055
6218,6219,NCTD_svsta,svsta,NaN,Sorrento Valley Station,32.902813,-117.225088,NCTD,32.902808,-117.225076
6219,6220,NCTD_visttc,visttc,NaN,Vista Transit Center,33.203240,-117.245070,NCTD,33.203235,-117.245058

In [61]:
# Looks like stop_code imitates stop_id whenever it is an integer. So we can drop stop_code

print('Dropping "stop_code"')
clean_transit_df = clean_transit_df.drop(columns='stop_code')
clean_transit_df

Dropping "stop_code"

,objectid,stop_uid,stop_id,stop_name,stop_lat,stop_lon,stop_agncy,lat,lng
0,1,MTS_11tbro,11tbro,11th Ave & Broadway,32.716268,-117.154649,MTS,32.716263,-117.154637
1,2,MTS_12tS,12tS,12th & Imperial Station,32.706002,-117.153378,MTS,32.705997,-117.153366
2,3,MTS_imtS,imtS,12th & Imperial Station Bayside,32.705229,-117.154318,MTS,32.705224,-117.154306
3,4,MTS_imp12,imp12,12th & Imperial Transit Center,32.705685,-117.152875,MTS,32.705680,-117.152863
4,5,MTS_24tS,24tS,24th Street Station,32.661854,-117.108017,MTS,32.661849,-117.108005
...,...,...,...,...,...,...,...,...,...
6215,6216,NCTD_pcrtc,pcrtc,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD,33.178271,-117.336513
6216,6217,NCTD_slrtc,slrtc,San Luis Rey Transit Center,33.254410,-117.298129,NCTD,33.254405,-117.298117
6217,6218,NCTD_solsta,solsta,Solana Beach Station,32.992937,-117.271067,NCTD,32.992932,-117.271055
6218,6219,NCTD_svsta,svsta,Sorrento Valley Station,32.902813,-117.225088,NCTD,32.902808,-117.225076
6219,6220,NCTD_visttc,visttc,Vista Transit Center,33.203240,-117.245070,NCTD,33.203235,-117.245058

In [62]:
# Looks like "stop_uid" is a combination of "stop_id" and "stop_agncy" so we can drop it

print('Dropping "stop_uid"')
clean_transit_df = clean_transit_df.drop(columns='stop_uid')
clean_transit_df

Dropping "stop_uid"

,objectid,stop_id,stop_name,stop_lat,stop_lon,stop_agncy,lat,lng
0,1,11tbro,11th Ave & Broadway,32.716268,-117.154649,MTS,32.716263,-117.154637
1,2,12tS,12th & Imperial Station,32.706002,-117.153378,MTS,32.705997,-117.153366
2,3,imtS,12th & Imperial Station Bayside,32.705229,-117.154318,MTS,32.705224,-117.154306
3,4,imp12,12th & Imperial Transit Center,32.705685,-117.152875,MTS,32.705680,-117.152863
4,5,24tS,24th Street Station,32.661854,-117.108017,MTS,32.661849,-117.108005
...,...,...,...,...,...,...,...,...
6215,6216,pcrtc,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD,33.178271,-117.336513
6216,6217,slrtc,San Luis Rey Transit Center,33.254410,-117.298129,NCTD,33.254405,-117.298117
6217,6218,solsta,Solana Beach Station,32.992937,-117.271067,NCTD,32.992932,-117.271055
6218,6219,svsta,Sorrento Valley Station,32.902813,-117.225088,NCTD,32.902808,-117.225076
6219,6220,visttc,Vista Transit Center,33.203240,-117.245070,NCTD,33.203235,-117.245058

In [63]:
# lets take a closer look at the differences between stop_lat/lon and lat/lng

coord_df = clean_transit_df.copy()
coord_df['lat_diff'] = round(coord_df['stop_lat'] - coord_df['lat'], 6)
coord_df['lon_diff'] = round(coord_df['stop_lon'] - coord_df['lng'], 6)
print(coord_df['lat_diff'].value_counts())
print(coord_df['lon_diff'].value_counts())

print('\n The difference is very minimal and uniform so we can use stop_lat/lon going forward')
clean_transit_df = clean_transit_df.drop(columns=['lat','lng'])
clean_transit_df

lat_diff
0.000005    6220
Name: count, dtype: int64
lon_diff
-0.000012    6220
Name: count, dtype: int64

 The difference is very minimal and uniform so we can use stop_lat/lon going forward

,objectid,stop_id,stop_name,stop_lat,stop_lon,stop_agncy
0,1,11tbro,11th Ave & Broadway,32.716268,-117.154649,MTS
1,2,12tS,12th & Imperial Station,32.706002,-117.153378,MTS
2,3,imtS,12th & Imperial Station Bayside,32.705229,-117.154318,MTS
3,4,imp12,12th & Imperial Transit Center,32.705685,-117.152875,MTS
4,5,24tS,24th Street Station,32.661854,-117.108017,MTS
...,...,...,...,...,...,...
6215,6216,pcrtc,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD
6216,6217,slrtc,San Luis Rey Transit Center,33.254410,-117.298129,NCTD
6217,6218,solsta,Solana Beach Station,32.992937,-117.271067,NCTD
6218,6219,svsta,Sorrento Valley Station,32.902813,-117.225088,NCTD
6219,6220,visttc,Vista Transit Center,33.203240,-117.245070,NCTD

In [64]:
print('Now we will load the new clean_transit_df data into "data/02-processed"')

import os
folder_name = 'Group022_WI26/data/02-processed'
file_name = 'clean_transit_stops_datasd.csv'
full_path = os.path.join(folder_name, file_name)

# Make sure folder exists
os.makedirs(folder_name, exist_ok=True)

# Save the CSV in the correct folder
clean_transit_df.to_csv(full_path, index=False)

print(f"Data saved to {full_path}")

Now we will load the new clean_transit_df data into "data/02-processed"
Data saved to Group022_WI26/data/02-processed/clean_transit_stops_datasd.csv

### Dataset #2 

See instructions above for Dataset #1.  Feel free to keep adding as many more datasets as you need.  Put each new dataset in its own section just like these. 

Lastly if you do have multiple datasets, add another section where you demonstrate how you will join, align, cross-reference or whatever to combine data from the different datasets

Please note that you can always keep adding more datasets in the future if these datasets you turn in for the checkpoint aren't sufficient.  The goal here is demonstrate that you can obtain and wrangle data.  You are not tied down to only use what you turn in right now.

In [ ]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them