# COGS 108 - Data Checkpoint

## Authors

<!-- This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing -->

- Lola Wang: Conceptualization (Data ethics), Writing – original draft
- Adrienne Riley: Research question and hypothesis, Data curation (Cleaning, Overview)
- Sharon Kodali: Writing – review & editing, Data curation (Cleaning)
- Summer Garvais: Background research, Data curation (Cleaning)
- Kai Arizabal: Conceptualization (Data plan), Writing – original draft

## Research Question

Is there an association between increased ridership at San Diego Trolley stations and nearby crime rates over time? Are these effects different across neighborhood socioeconomic contexts?

## Background and Prior Work

Many people argue against the implementation of public transportation in their neighborhoods, citing its tendency to bring crime into their communities. But is this really true? Much research has been done looking into the relationship between public transportation and crime rates and different conclusions have been drawn. Some claim that public transportation can “import” crime into wealthy neighborhoods, leading to higher than normal crime rates. Others see this crime “import” effect as unconvincing, and instead find public transportation alleviates socioeconomic stressors which provoke people into doing crime in the first place.

An issue presented when studying public transportation, particularly discerning its impact on crime rates, is the seeming lack of A/B testing. A place that has access to public transportation and one that doesn’t cannot typically be tested against each other without accounting for a multitude of external factors. This makes sense because many things contribute to whether or not a place is given the opportunity to have public transportation or not. In a clever attempt to navigate this issue, David C. Phillips and Danielle Sandler<a name="cite_note-1"></a> [^](#cite_ref-1) wrote a paper analyzing crime rates in the Washington D.C. area when certain transit stations were closed. The paper found that crime decreases across the railway network when stations are closed and that the decrease in crime was felt more in areas where fewer offenders lived. In essence, the closure of stations can inhibit how easily criminals can navigate the network.

Another project, completed by Greg Ridgeway and John MacDonald, looked more holistically at the railway network in Los Angeles over a 27 year span from 1988-2014.<a name="cite_note-2"></a> [^](#cite_ref-2) They conclude that there is little evidence that access to public railways lead to an increase in crime in neighborhoods. While they do concede that criminals could use railways to travel to lower crime, wealthy areas to find victims, they argue that access to public transportation could lower overall crime rates in a metropolitan area. They claim that giving public transit access to people who hail from low socioeconomic areas can help them seek better opportunities rather than resort to crime.

Looking through the lens of public safety, Tanya Lewis writes an article detailing how public transportation results in far fewer deaths and fewer crimes than automobile travel. <a name="cite_note-3"></a> [^](#cite_ref-3) Per 1 billion passenger miles traveled in 2022, automobiles caused 16.8 fatalities in rural areas and 11.5 in urban areas. To contrast, rail transit fatalities were 5.9 per 1 billion miles and many were non-occupant fatalities that resulted from suicide. Additionally, crimes like assault, robbery, and homicide are down on public transportation in 2023 compared to in 2019 while motor vehicle theft and road rage incidents involving guns are up. The article suggests that many people feel more unsafe on public transportation than they should according to the statistics.

Diving deeper into this phenomenon, Anastasia Loukaitou-Sideris and Camille Fink address the fear women feel when using public transportation.<a name="cite_note-4"></a> [^](#cite_ref-4) Women will often avoid certain railways, only use them in the day, or forego public transportation altogether due to fear of victimization. According to Loukaitou-Sideris and Fink, much of this blame should be put into the lack of input women get when designing safety procedures for public transportation. Citing the lack of security, cameras, panic buttons, or other bystanders who could help, the authors argue that women will continue to avoid public transportation so long as there is no greater attempt to prevent crime around transportation infrastructure like bus stops, trains etc. If public transportation does in fact have a way of bringing crime to certain areas, increased security around transit stops could potentially help to mitigate this.


1. <a name="cite_note-1"></a> [^](#cite_ref-1) Phillips, David C., and Danielle Sandler. “Does Public Transit Spread Crime? Evidence from Temporary Rail Station Closures.” Regional Science and Urban Economics, vol. 52, 2015, pp. 13–26, https://doi.org/10.1016/j.regsciurbeco.2015.02.001
2. <a name="cite_note-2"></a> [^](#cite_ref-2)Ridgeway, Greg, and John M. MacDonald. Effect of Rail Transit on Crime: A Study of Los Angeles from 1988–2014. Department of Criminology Working Paper No. 2015-14.0, University of Pennsylvania, 2015, crim.sas.upenn.edu/sites/default/files/2015-14.0_Ridgeway_MacDonald_RailEffect%281%29.pdf.
3. <a name="cite_note-3"></a> [^](#cite_ref-3)Lewis, Tanya. “Is Public Transit Really Safer Than Driving?” Scientific American, 15 Apr. 2025, www.scientificamerican.com/article/is-public-transit-really-safer-than-driving/
4. <a name="cite_note-4"></a> [^](#cite_ref-4) Loukaitou-Sideris, Anastasia, and Camille Fink. “Addressing Women’s Fear of Victimization in Transportation Settings: A Survey of U.S. Transit Agencies.” Urban Affairs Review, vol. 44, no. 4, 2008, pp. 554–587, https://doi.org/10.1177/1078087408322874

## Hypothesis

We hypothesize that the relationship between San Diego Trolley ridership and nearby crime rates over time will be weak or mixed, rather than uniformly positive or negative. This is because we expect that any observed differences in crime patterns will be driven largely by preexisting neighborhood socioeconomic conditions, rather than the transit use itself. This aligns with prior research suggesting public transit is often blamed for crime patterns that reflect broader structural inequities rather than transit use.

Null Hypothesis: Changes in San Diego Trolley ridership have no association with nearby crime rates over time.

Alternative Hypothesis: Any association between trolley ridership and crime varies across neighborhoods and is more strongly related to socioeconomic context than to ridership levels alone.

## Data

### Data overview

- Dataset #1
  - Dataset Name: Transit Stops Data
  - Link to the dataset:
     csv file: https://raw.githubusercontent.com/COGS108/Group022_WI26/refs/heads/master/data/00-raw/transit_stops_datasd.csv
  found on: https://data.sandiego.gov/datasets/transit-stops/ 
  - Number of observations: 6220
  - Number of variables: 14
  - variables most relevant to this project: 
  The most relevant variables in this dataset are stop_name, stop_lat, and stop_lon. These provide the geographic location of each transit stop. These latitude and longitude coordinates allow us to map stop locations and consider spatial patterns across San Diego. The stop_id and stop_code uniquely identify each transit stop and might be helpful for potential merging with other transit-related datasets.
  - shortcomings of this dataset:
    This data set has strictly static information and does not include ridership data, service frequency, route information, demographic/socioeconomic context, or temporal variables. Because of this, it cannot directly measure usage patterns or equity without being combined with additional datasets.
- Dataset #2
  - Dataset Name: 2025 Crime Rates Data
  - Link to the dataset: https://www.sandiego.gov/sites/default/files/2026-02/nibrs-crime-rates-per-1000-residents-2025.pdf
  - Number of observations: 125
  - Number of variables: 23
  - The most relevant variables are: `Neighborhood`, the unique ID for this dataset and `[Simple Assault, Intimidation, Robbery, Larceny, Theft From Motor Vehicle, Motor Vehicle Theft, Vandalism, Drug/Narcotic Violations]`. These are several crime categories that are commonly related to the trolley lines and public transit in general.
  - Shortcomings of this dataset: This data has no temporal granularity and basic spatial granularity. While the crime can be identified by the neighborhood, we cannot locate the specific coordinates or address and time of any incidents. This will make inferring a causal relationship between SD crimes and trolley lines more difficult.

<!-- If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets. -->

We can combine, or at least cross-reference, the datasets based on location. We can do so by using the geographic data from Dataset #1 and identifying which neighborhood each transit stop is located in.

In [17]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [18]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data
import pandas as pd

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://datahub.ucsd.edu/hub/user-redirect/lab/tree/Group022_WI26/data/00-raw/transit_stops_datasd.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading transit_stops_datasd.csv:   0%|          | 0.00/287k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  2.86it/s]

Successfully downloaded: transit_stops_datasd.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  5.16it/s]

Successfully downloaded: bad-drivers.csv

### Dataset #1: Transit Stops Attribute Data

The Transit Stops dataset contains geographic and identifying information for public transit stops across the San Diego region (MTS and NCTD). The dataset includes 6,220 observations and 14 variables, with each row representing one transit stop. 的The most important quantitative metrics in the Transit Stops dataset are the spatial coordinates stop_lat and stop_lon (also listed as LAT and LNG for more decimal places).These variables record the geographic position of each transit stop using decimal degree units. Latitude measures north–south position relative to the equator, while longitude measures east–west position relative to the prime meridian. In this dataset, latitude values range roughly from 32.5 to 33.0 degrees, and longitude values range from approximately –117.3 to –116.9 degrees, which corresponds to the broader San Diego County region. These coordinate metrics allow us to map stop locations, calculate spatial distances, and maybe infer correlations, making them foundational for spatial crime analysis.

Another operational metric is the wheelchair, which is recorded as a categorical numeric indicator rather than a continuous measure. The wheelchair accessibility variable follows the General Transit Feed Specification (GTFS) standard, where 0 indicates no accessibility information, 1 indicates wheelchair-accessible boarding, and 2 indicates non-accessible stops. In this dataset, values appear as “0E-8,” which is a scientific notation formatting issue but functionally corresponds to 0 (unknown accessibility status). This metric reflects infrastructure accessibility and may indicate variation in station investment or design equity.

Other identifiers such as stop_id and stop_code function as nominal variables used to identify the stop. They uniquely identify each stop but have no units or ordinal or numerical meaning. 

One major concern with this dataset is that it is not real-time or recorded with time. The data provide a static snapshot of where transit stops are located, but they do not include any information about ridership levels, service frequency, or how ridership changes over time. Because of this, the dataset cannot capture actual transit activity or passenger volume. For our research question, this is important because crime patterns are more likely related to how many people are using a station rather than simply whether a stop exists at that location.

Another limitation is the lack of neighborhood contextual information. The dataset does not include demographic, socioeconomic, or land-use variables for the areas surrounding each stop. Transit stops are often located in neighborhoods with different income levels, population densities, and built environments, all of which may influence crime rates independently of transit use. Without incorporating these contextual factors, it is difficult to determine whether any observed crime patterns are associated with transit ridership or with preexisting neighborhood conditions.

In [1]:
# Drop any rows or columns are completely null
clean_transit_df = transit_df.dropna(how='all', axis=0)
clean_transit_df = transit_df.dropna(how='all', axis=1)

In [57]:
# Shape of dataset
print(f'Columns in dataset: {clean_transit_df.shape[1]}\nRows in dataset: {clean_transit_df.shape[0]}')

Columns in dataset: 14
Rows in dataset: 6220

In [58]:
# Seeing what percent of columns have null values
empty_columns = list()
for col in clean_transit_df.columns:
    if ((clean_transit_df.shape[0] - clean_transit_df[col].count()) / clean_transit_df.shape[0]) * 100 > 5:
        empty_columns.append(col)
        
    print(f'{col}: {round(((clean_transit_df.shape[0] - clean_transit_df[col].count()) / clean_transit_df.shape[0]) * 100, 2)}% null\n----------------------')

objectid: 0.0% null
----------------------
stop_uid: 0.0% null
----------------------
stop_id: 0.0% null
----------------------
stop_code: 1.85% null
----------------------
stop_name: 0.0% null
----------------------
stop_lat: 0.0% null
----------------------
stop_lon: 0.0% null
----------------------
stop_agncy: 0.0% null
----------------------
wheelchair: 29.5% null
----------------------
intersec: 5.31% null
----------------------
stop_place: 72.86% null
----------------------
parent_sta: 95.08% null
----------------------
lat: 0.0% null
----------------------
lng: 0.0% null
----------------------

In [59]:
# Focusing on columns which have null values over 5% (I will call them empty_columns)

for col in empty_columns:
    print(f'Different kinds of values in {col}:')
    print(clean_transit_df[col].value_counts())
    print('-----------------')

Different kinds of values in wheelchair:
wheelchair
1.0    3174
0.0     741
2.0     470
Name: count, dtype: int64
-----------------
Different kinds of values in intersec:
intersec
F-W/B             815
F-E/B             798
F-N/B             759
F-S/B             727
N-W/B             522
N-E/B             490
N-S/B             450
N-N/B             434
M-Street-E/B      214
M-Street-W/B      177
M-TC-Bus          167
M-Street-S/B      132
M-Street-N/B      119
M-Special_Loc      48
M-TC-Train-N/B     18
M-TC-Train-S/B     14
M-TC-Train-E/B      4
M-TC-Train-W/B      2
Name: count, dtype: int64
-----------------
Different kinds of values in stop_place:
stop_place
esctc     12
euctro    10
mirsta    10
iritro    10
ecajtc    10
          ..
lvgenW     1
lvgenE     1
lvgenS     1
kearny     1
pacpac     1
Name: count, Length: 1029, dtype: int64
-----------------
Different kinds of values in parent_sta:
parent_sta
esctc     12
iritro    10
ecajtc    10
euctro    10
fasvtc    10
          ..
peptc      1
genljN     1
amptro     1
sanS       1
i15els     1
Name: count, Length: 110, dtype: int64
-----------------

In [60]:
# The columns look to either be irrelevant to our project or too imcomplete to evaluate
# So lets drop them

print('Dropping empty_columns')
clean_transit_df = clean_transit_df.drop(columns=empty_columns)
clean_transit_df

Dropping empty_columns

,objectid,stop_uid,stop_id,stop_code,stop_name,stop_lat,stop_lon,stop_agncy,lat,lng
0,1,MTS_11tbro,11tbro,NaN,11th Ave & Broadway,32.716268,-117.154649,MTS,32.716263,-117.154637
1,2,MTS_12tS,12tS,NaN,12th & Imperial Station,32.706002,-117.153378,MTS,32.705997,-117.153366
2,3,MTS_imtS,imtS,NaN,12th & Imperial Station Bayside,32.705229,-117.154318,MTS,32.705224,-117.154306
3,4,MTS_imp12,imp12,NaN,12th & Imperial Transit Center,32.705685,-117.152875,MTS,32.705680,-117.152863
4,5,MTS_24tS,24tS,NaN,24th Street Station,32.661854,-117.108017,MTS,32.661849,-117.108005
...,...,...,...,...,...,...,...,...,...,...
6215,6216,NCTD_pcrtc,pcrtc,NaN,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD,33.178271,-117.336513
6216,6217,NCTD_slrtc,slrtc,NaN,San Luis Rey Transit Center,33.254410,-117.298129,NCTD,33.254405,-117.298117
6217,6218,NCTD_solsta,solsta,NaN,Solana Beach Station,32.992937,-117.271067,NCTD,32.992932,-117.271055
6218,6219,NCTD_svsta,svsta,NaN,Sorrento Valley Station,32.902813,-117.225088,NCTD,32.902808,-117.225076
6219,6220,NCTD_visttc,visttc,NaN,Vista Transit Center,33.203240,-117.245070,NCTD,33.203235,-117.245058

In [61]:
# Looks like stop_code imitates stop_id whenever it is an integer. So we can drop stop_code

print('Dropping "stop_code"')
clean_transit_df = clean_transit_df.drop(columns='stop_code')
clean_transit_df

Dropping "stop_code"

,objectid,stop_uid,stop_id,stop_name,stop_lat,stop_lon,stop_agncy,lat,lng
0,1,MTS_11tbro,11tbro,11th Ave & Broadway,32.716268,-117.154649,MTS,32.716263,-117.154637
1,2,MTS_12tS,12tS,12th & Imperial Station,32.706002,-117.153378,MTS,32.705997,-117.153366
2,3,MTS_imtS,imtS,12th & Imperial Station Bayside,32.705229,-117.154318,MTS,32.705224,-117.154306
3,4,MTS_imp12,imp12,12th & Imperial Transit Center,32.705685,-117.152875,MTS,32.705680,-117.152863
4,5,MTS_24tS,24tS,24th Street Station,32.661854,-117.108017,MTS,32.661849,-117.108005
...,...,...,...,...,...,...,...,...,...
6215,6216,NCTD_pcrtc,pcrtc,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD,33.178271,-117.336513
6216,6217,NCTD_slrtc,slrtc,San Luis Rey Transit Center,33.254410,-117.298129,NCTD,33.254405,-117.298117
6217,6218,NCTD_solsta,solsta,Solana Beach Station,32.992937,-117.271067,NCTD,32.992932,-117.271055
6218,6219,NCTD_svsta,svsta,Sorrento Valley Station,32.902813,-117.225088,NCTD,32.902808,-117.225076
6219,6220,NCTD_visttc,visttc,Vista Transit Center,33.203240,-117.245070,NCTD,33.203235,-117.245058

In [62]:
# Looks like "stop_uid" is a combination of "stop_id" and "stop_agncy" so we can drop it

print('Dropping "stop_uid"')
clean_transit_df = clean_transit_df.drop(columns='stop_uid')
clean_transit_df

Dropping "stop_uid"

,objectid,stop_id,stop_name,stop_lat,stop_lon,stop_agncy,lat,lng
0,1,11tbro,11th Ave & Broadway,32.716268,-117.154649,MTS,32.716263,-117.154637
1,2,12tS,12th & Imperial Station,32.706002,-117.153378,MTS,32.705997,-117.153366
2,3,imtS,12th & Imperial Station Bayside,32.705229,-117.154318,MTS,32.705224,-117.154306
3,4,imp12,12th & Imperial Transit Center,32.705685,-117.152875,MTS,32.705680,-117.152863
4,5,24tS,24th Street Station,32.661854,-117.108017,MTS,32.661849,-117.108005
...,...,...,...,...,...,...,...,...
6215,6216,pcrtc,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD,33.178271,-117.336513
6216,6217,slrtc,San Luis Rey Transit Center,33.254410,-117.298129,NCTD,33.254405,-117.298117
6217,6218,solsta,Solana Beach Station,32.992937,-117.271067,NCTD,32.992932,-117.271055
6218,6219,svsta,Sorrento Valley Station,32.902813,-117.225088,NCTD,32.902808,-117.225076
6219,6220,visttc,Vista Transit Center,33.203240,-117.245070,NCTD,33.203235,-117.245058

In [63]:
# lets take a closer look at the differences between stop_lat/lon and lat/lng

coord_df = clean_transit_df.copy()
coord_df['lat_diff'] = round(coord_df['stop_lat'] - coord_df['lat'], 6)
coord_df['lon_diff'] = round(coord_df['stop_lon'] - coord_df['lng'], 6)
print(coord_df['lat_diff'].value_counts())
print(coord_df['lon_diff'].value_counts())

print('\n The difference is very minimal and uniform so we can use stop_lat/lon going forward')
clean_transit_df = clean_transit_df.drop(columns=['lat','lng'])
clean_transit_df

lat_diff
0.000005    6220
Name: count, dtype: int64
lon_diff
-0.000012    6220
Name: count, dtype: int64

 The difference is very minimal and uniform so we can use stop_lat/lon going forward

,objectid,stop_id,stop_name,stop_lat,stop_lon,stop_agncy
0,1,11tbro,11th Ave & Broadway,32.716268,-117.154649,MTS
1,2,12tS,12th & Imperial Station,32.706002,-117.153378,MTS
2,3,imtS,12th & Imperial Station Bayside,32.705229,-117.154318,MTS
3,4,imp12,12th & Imperial Transit Center,32.705685,-117.152875,MTS
4,5,24tS,24th Street Station,32.661854,-117.108017,MTS
...,...,...,...,...,...,...
6215,6216,pcrtc,Plaza Camino Real Transit Center,33.178276,-117.336525,NCTD
6216,6217,slrtc,San Luis Rey Transit Center,33.254410,-117.298129,NCTD
6217,6218,solsta,Solana Beach Station,32.992937,-117.271067,NCTD
6218,6219,svsta,Sorrento Valley Station,32.902813,-117.225088,NCTD
6219,6220,visttc,Vista Transit Center,33.203240,-117.245070,NCTD

In [91]:
import os

# Define folder path relative to the GitHub repo root
folder_name = os.path.join('data', '02-processed')
file_name = 'clean_transit_stops_datasd.csv'
full_path = os.path.join(folder_name, file_name)

# Create the folder if it doesn't exist
os.makedirs(folder_name, exist_ok=True)

# Save the DataFrame to CSV in the repo folder
clean_transit_df.to_csv(full_path, index=False)

print(f'Data successfully saved to "{full_path}"')

Data successfully saved to "data/02-processed/clean_transit_stops_datasd.csv"

### Dataset #2: 2025 Crime Rates Data

This crime dataset reports crime rates for neighborhoods in San Diego throughout 2025. There are 125 observations, each being a SD neighborhood, and 23 variables, each being a different offense. Besides the Neighborhood column (the unique ID), the data are on the same unit scale of crime per 1,000 residents for the neighborhood. This specific metric allows us to compare crime across neighborhoods and crime “density” to trolley activity, regardless of each neighborhood’s population. Among these different crime offense rates, the most important measures for our research are `[Simple Assault, Intimidation, Robbery, Larceny, Theft From Motor Vehicle, Motor Vehicle Theft, Vandalism, Drug/Narcotic Violations]`. These crimes are intuitively related to public transit because they often occur during commutes or at transit stops, where high foot traffic and accessibility provide opportunities for criminal activity.

To understand the specific scale of crime per 1,000 residents, we can look at the larceny crime rates—the most common public- and transit- related crime. The average “larceny” rate is 15.74, which means that for every 1,000 people, we expect roughly 16 offenses were reported in 2025. Similarly, a rate of 7.88 for vandalism means for every 1,000 people, there were about 8 reported offenses.

Although the data is normalized per 1,000 residents, we cannot easily say that high crime rates indicate “high crime neighborhoods" because these rates often reflect crimes from any person against the permanent resident population. Therefore, we must consider if these neighborhoods have high traffic or massive tourism like Mission Bay, or serve as a central connection hub for many public transit services like Old Town. Ultimately, the influx of people artificially inflates the crime rates relative to the number of residents. However, taking this into consideration, we can use this to our advantage to infer if inflation is related to trolley operations.

Like Dataset #1, one major concern with this dataset is the lack of temporal granularity. Since it only provides aggregated crime rates for the year 2025, the data do not distinguish between crimes that occur during peak hours—high ridership—or during low activity hours. This makes it difficult to definitively prove a causal relationship between transit activities and crime without additional information on each crime incident.

Another concern with this dataset is that it only includes crimes that were officially reported to and recorded by the SD Police Department. Many incidents go unreported for multiple reasons, including no or delayed responses by police or distrust of law enforcement. Additionally, there is potential for false police reports in this data that may affect  our analysis of socioeconomic factors.

In [1]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

## Ethics

### A. Data Collection
 - [x] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

> Our project uses publicly available ridership and police-reported crime datasets, both of which are subject to systemic collection biases. Crime data reflected reported incidents rather than absolute true crime occurence and the accuracy of reports may vary across neighborhoods due to diffences in policing intensity, community trust in law enforcement and other factors. Ridership data may also overrepresent frequent riders rather than number of separate individuals. To address these concerns, we plan to be midful of these limitations when interpreting results, consider normalization of our data, and avoid drawing strong causal and opinionated conclussions from raw counts alone.

 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

### B. Data Storage
 - [x] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?

 - [x] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?

 - [x] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?

> While our analysis is quantitative, we recognize that our project may imply a sentiment towards the transit system, local communities, commuters and neighborhoods. To reduce potential blindspots, we plan to incorporate a wide range of relevant datasets where available, such as ridership patterns, crime statistics, and neighborhood-level socioeconomic indicators.

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?

> We are aware that dataset bias may arise from uneven data coverage since some trolley stations are more recently built than others, imbalanced station activity levels, and other variables. To mitigate these issues, we plan to incorporate relevant variables, test altervative models, and examine whether results are sensitive to different assumptions. This allow us to better assess the persuasivenees of observed patterns and reduce the risk of misleading conclusions.

 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?

> When presenting results, we aim to design visualizations that accurately and transparently our data and analysis. This includes using consistent axis scales across comparable plots, avoiding visual distortions that could create exaggerated or misleading trends. Clearly labeling units and time ranges is also important to keep authenticity. In addition, using different plots and graphs to represent complex patterns rather than descriptive statistics to avoid oversimplyfying is something we should consider as well.

 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?

 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

> To support the reproducibility and transparency of our project, we plan to document our data, analysis and models in every step in a clear and organized manner. Code and intermediate outputs will be well recorded to allow others to rretrace the analysis pipeline if needed. This can help us ensure that potential errors can be identified easily and results can be tested or extended in later stages of our project. 

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?

 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?

> Our analysis may vary across neighborhoods with different socioeconomic characteristics, which could lead to misleading interpretations of results. We can examine results across different  subgroups. By comparing patterns across these groups, we can better understand whether observed relationships between ridership and crime differ systematically by context. This subgroup-based perspective helps us interpret findings more carefully and reduces the risk of drawing conclusions that may disproportionately reflect only certain groups.

 - [X] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?

> We are aware that the choice of evalustion metics can influence how results are interpreted. Rather than relying on a single measure, we plan to explore multiple complementary metrics, such as crime counts, normalized crime rates, ridership growth percentages, and other relevant statistics. Considering multiple perspectives allows for a more informed understanding of our research question.

 - [X] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?

> To address this concers, we can prioritize interpretability when selecting analytical models and presenting results. Model outputs will be explained in understandable language and terms. This helps ensure that findings can be meaningfully interpreted by non-technical audiences and supports transparent communication of analytical outcomes.

 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

> We will clearly commubicate the limitations of this study, including observational nature of the data, potential reporting biases, the presence of unmeasured confounding variables and that we cannot establish causal relationships in our project. For example, we acknowledge that reported crime rate does not equal absolute true crime occurence.

### E. Deployment
 - [x] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?

 - [X] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?

 - [x] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary？

> It is important to be able to revise or modify an analysis approach if issues are identifies. If problematic patterns, misleading results or unintended interpretations emerge during the project, we can adjust model specifications, go back and trace our documented analysis and codes to correct the errors or remove certain analysis from the final report. By doing that, we intend to prevent the presentation of results that may be inaccurate or potentially harmful.

 - [x] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?

> The findings from this project could be misinterpreted or used in unintended ways, such as reinforcing negative stereotypes about the transit system or certain neighborhoods. To reduce this risk, we plan to carefully frame results, avoid opinionated conclusions, and emphasize contextual factors and limitations.

## Team Expectations

### Communication
- We will communicate through text.
- Be responsive. We expect responses within 24 hours.
- Notify ahead of time if we will be unavailable.
- Notify each other before making big project changes.
- Meet at least once a week (in-person preferred).
- Treat each other with respect and allow everyone to voice opinions.

### Contribution
- Distribute work evenly based on skills and strengths.
- Set clear deadlines and expectations for tasks.
- Assign tasks with clear ownership and deadlines.
- Maintain and update the project timeline as we progress.
- Assume feedback is well-intended and aimed at improving the project.
- Constructive feedback is welcome.

### Struggles & Delays
- Communicate early if anyone is struggling.
- Redistribute tasks if needed to keep the project on track.
- Support teammates while maintaining accountability.
- If a member repeatedly fails to contribute, we will communicate expectations and allow a one-week improvement window; if no improvement, we will contact the instructor/TA.

## Project Timeline Proposal


| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 2/4  |  12:30 PM | Brainstorm topics and how to approach research question, find datasets  | Project Proposal | 
| 2/11  |  12:30 PM |Consider what visualizations could be useful in project, import and wrangle data | Create a strategy for how we will answer the research question | 
| 2/17  | 3:30 PM  | Finding appropriate datasets  | Data Checkpoint|
| 2/25  | 12 PM  |Select what data sets well be working with |Clean data and organize into notebook|
| 3/3  | 3:30 PM  | Begin analysis|EDA checkpoint |
| 3/17  | 3:30 PM  | Make sure our notebook is clean. Breakdown of how we are approaching the video.|Final project + Video |