# Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

Scoring: Out of 18 points in total.  15 points in the report.  3 points in the video summary of your report for a non-technical audience.

For the report:
- Each Developing  => -0.5 pts
- Each Unsatisfactory/Missing => -1 pts
  - until the score is 0

For the video:
- Developing  => -1.5 pts
- Unsatisfactory/Missing => -3 pts

|                                                                                    | Unsatisfactory                                                                                                                                                                                                                                                                                      | Developing                                                                                                                                                                                                                                                                                                                          | Proficient                                                                                                                                                                                                                                                    | Exellent                                                                                                                                                                                                                                                                                                                                                          |
| ---------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Title & abstract                                                                   | Title or abstract is confusing or fails to offer important details about the question, variables, context, or methods of the project.                                                                                                                                                               | Title or abstract lacks relevance or fails to offer appropriate details about the question, variables, context, or methods of the project.                                                                                                                                                                                          | Title and abstract are relevant, offering sufficient details about the research project.                                                                                                                                                                      | Title and abstract are informative, succinct, and clear. It offers specific details about the question, variables, context, and proposed methods of the study.                                                                                                                                                                                                    |
| Background                                                                         | Did not have at least 3 reliable and relevant sources. Or relevant sources were not used in relevant ways                                                                                                                                                                                           | A key component was not connected to the research literature. Selected literature was from unreliable sources. Literary supports were vague or ambiguous.                                                                                                                                                                           | Key research components were connected to relevant, reliable literature.                                                                                                                                                                                      | Narrative integrates critical and logical details from the peer-reviewed or other professional research literature. Each key research component is grounded to the literature. Attention is given to different perspectives, threats to validity, and opinion vs. evidence.                                                                                       |
| Research question & hypothesis                                                     | Research issue remains unclear. The research purpose, questions, hypotheses, definitions or variables and controls are still largely undefined, or when they are are poorly formed, ambiguous, or not logically connected to the description of the problem. Unclear connections to the literature. | Research issue is identified, but statement is too broad or fails to establish the importance of the problem. The research purpose, questions, hypotheses, definitions or variables and controls are poorly formed, ambiguous, or not logically connected to the description of the problem. Unclear connections to the literature. | Identifies a relevant research issue. Research questions are succinctly stated, connected to the research issue, and supported by the literature. Variables and controls have been identified and described. Connections are established with the literature. | Presents a significant research problem related to the chemical sciences. Articulates clear, reasonable research questions given the purpose, design, and methods of the project. All variables and controls have been appropriately defined. Proposals are clearly supported from the research and theoretical literature. All elements are mutually supportive. |
| Data description                                                                   | Did not have references to relevant data sources for this problem. Did not describe the data obtained at those sources                                                                                                                                                                              | A key data source was not referenced or described in satisfactory level of detail                                                                                                                                                                                                                                                   | All relevant data sources were referenced and described in terms of their key variables and size                                                                                                                                                              | Multiple data sources for each aspect of the project, All data sources are fully described and referenced. The details of the descriptions also make it clear how they support the needs ot the project.                                                                                                                                                          |
| Data wrangling                                                                     | Data obviously not tidy and not clean. Or even if they are clean/tidy, there was no demonstration of that fact                                                                                                                                                                                      | Data has some minor problems with tidiness or cleanliness. Potentially these are not problems but it wasn't fully demonstrated to be the case in the code                                                                                                                                                                           | Data are made tidy and clean, or are clearly demonstrated to be so from download                                                                                                                                                                              | Data wrangling is complete, but also particularly thoroughly done for a very tough case. Often free text parsing is a bear like this, and doing it well can mean a million edge cases.                                                                                                                                                                            |
| Data visualizations                                                                | Many plots don't capture useful information, or their display of information is difficult to understand.. Legends, labels, axes, titles, captions, etc of many plots may be poor or missing. Figures are not referenced in the main text.                                                           | Most plots make sense and capture useful information. Legends, labels, axes, titles, captions, etc are mostly legible and adequately describe the content of the figure. Most figures are referenced or explained inside the main text and not just left hanging.                                                                   | Plots make sense and capture useful information. Legends, labels, axes, titles, captions, etc are clearly legible and adequately describe the content of the figure. Figures are referenced or explained inside the main text and not just left hanging.      | Plots are beautiful and information dense. Legends, labels, axes, titles, captions, etc clearly describe the content of the figure. Figures are well integrated with the text.                                                                                                                                                                                    |
| Data analysis and results                                                          | Lacks any metrics or at least metrics that are relevant to the problem                                                                                                                                                                                                                              | Some metrics selected are not appropriate for the problem or the metrics selected are not described sufficiently                                                                                                                                                                                                                    | All metrics described are appropriate and and described sufficiently                                                                                                                                                                                          | The metrics are described clearly and succinctly. Their appropriateness for addressing the research problem is clearly described.                                                                                                                                                                                                                                 |
| Ethics                                                                             | Only tries a baseline model, never advances to proper model/hyper-parameter selection                                                                                                                                                                                                               | Only investigates one minimal aspect of their problem, e.g. just did a single hyperparameter selection on a single model                                                                                                                                                                                                            | Does a good model/hyper-parameter selection. Only attempts minimal secondary analysis                                                                                                                                                                         | Does a good model/hyper-parameter selection. Performs multiple secondary analysis such as learning curves, heat maps looking at where in the parameter space things are good/bad, uses statistical testing                                                                                                                                                        |
| Conclusion and discussion                                                          | Doesn't have a narrative/conclusions of what the report accomplished. Or very minimal conclusions, like "X was best" without anything else                                                                                                                                                          | Has narrative/conclusions, but it feels perfunctory and lacks context. Especially if the limitations and ethics sections are largely junk or missing                                                                                                                                                                                | Properly recapitulates the results and provides context for them. Has a sense of the limitatins and ethical issues.                                                                                                                                           | Clearly recapitulates the results and provides context, including the literature/background Has a sense of what to do next, and has good explorations of the limitations and ethics.                                                                                                                                                                              |
| Documentation and written communication                                            | Code documentation is non-existent or perfunctory. Writing has usage errors, poor fluency, and poor rhetoric. If doc/writing are both like this you get unsatisfacory. If one is unsatisfactory and the other is developing you still get unsatisfactory overall.                                   | Code documentation is only partially there. Writing has some usage errors, some poor fluency, or some poor rhetoric. If doc/writing are both like this you get developing. If one is developing and the other is satisfactory you still get developing.                                                                             | Code is documented throughout. Writing has good fluency, good rhetoric, and at most a few minor errors.                                                                                                                                                       | Code documentation is highly informative with docstrings. Writing is high quality. If both doc/writing are like this you get excellent. If one is satisfactory and the other excellent you still get satisfactory.                                                                                                                                                |
| Video (developing -1.5 points, unsatisfactory -3 points)                           | Video well outside the 3-5min time range. Does not communicate major results at a non-technical level. Has major technical issues such as no sound or not available at link. Unsatisfactory if 2/3 of these are true                                                                                | Video just outside the 3-5min time range. Does not communicate well on some points (either wrong tech level or just confusing). Has technical issues such as poor speech quality on video. Developing if 2/3 of these are true                                                                                                      | Video has good quality and is in within 3-5 min range. Communicates the major results at an accessible level for non-technical people.                                                                                                                        | Video has high production quality and is in within 3-5 min range. Communicates the major results clearly and gives a sense of the methods at an accessible level for non-technical people. Has a wow factor (e.g. funny or original approach)                                                                                                                     |
| Quality modifier (can result in extra credit beyond 18 points for this assignment) | Almost everything was just barely proficient. Lots of minimal effort work. Do not double punish; if they already lost points on the rubric do not invoke this: -0.5 points                                                                                                                        |                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                       More than 5 excellents on this rubric: +0.5 points                                                                                   |

# COGS 108 - Final Project (change this to your project's title)

## Permissions

Place an `X` in the appropriate bracket below to specify if you would like your group's project to be made available to the public, including the names of the authors.

* [  ] YES - make available
* [  ] NO - keep private

## Link to video
https://link.to.your.publicly.viewable.video

## Abstract

Please write one to four paragraphs that describe a very brief overview of why you did this, how you did, and the major findings and conclusions.

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Is there an association between increased ridership at San Diego Trolley stations and nearby crime rates over time? Are these effects different across neighborhood socioeconomic contexts?

## Background and Prior Work

Many people argue against the implementation of public transportation in their neighborhoods, citing its tendency to bring crime into their communities. But is this really true? Much research has been done looking into the relationship between public transportation and crime rates and different conclusions have been drawn. Some claim that public transportation can “import” crime into wealthy neighborhoods, leading to higher than normal crime rates. Others see this crime “import” effect as unconvincing, and instead find public transportation alleviates socioeconomic stressors which provoke people into doing crime in the first place.

An issue presented when studying public transportation, particularly discerning its impact on crime rates, is the seeming lack of A/B testing. A place that has access to public transportation and one that doesn’t cannot typically be tested against each other without accounting for a multitude of external factors. This makes sense because many things contribute to whether or not a place is given the opportunity to have public transportation or not. In a clever attempt to navigate this issue, David C. Phillips and Danielle Sandler<a name="cite_note-1"></a> [^](#cite_ref-1) wrote a paper analyzing crime rates in the Washington D.C. area when certain transit stations were closed. The paper found that crime decreases across the railway network when stations are closed and that the decrease in crime was felt more in areas where fewer offenders lived. In essence, the closure of stations can inhibit how easily criminals can navigate the network.

Another project, completed by Greg Ridgeway and John MacDonald, looked more holistically at the railway network in Los Angeles over a 27 year span from 1988-2014.<a name="cite_note-2"></a> [^](#cite_ref-2) They conclude that there is little evidence that access to public railways lead to an increase in crime in neighborhoods. While they do concede that criminals could use railways to travel to lower crime, wealthy areas to find victims, they argue that access to public transportation could lower overall crime rates in a metropolitan area. They claim that giving public transit access to people who hail from low socioeconomic areas can help them seek better opportunities rather than resort to crime.

Looking through the lens of public safety, Tanya Lewis writes an article detailing how public transportation results in far fewer deaths and fewer crimes than automobile travel. <a name="cite_note-3"></a> [^](#cite_ref-3) Per 1 billion passenger miles traveled in 2022, automobiles caused 16.8 fatalities in rural areas and 11.5 in urban areas. To contrast, rail transit fatalities were 5.9 per 1 billion miles and many were non-occupant fatalities that resulted from suicide. Additionally, crimes like assault, robbery, and homicide are down on public transportation in 2023 compared to in 2019 while motor vehicle theft and road rage incidents involving guns are up. The article suggests that many people feel more unsafe on public transportation than they should according to the statistics.

Diving deeper into this phenomenon, Anastasia Loukaitou-Sideris and Camille Fink address the fear women feel when using public transportation.<a name="cite_note-4"></a> [^](#cite_ref-4) Women will often avoid certain railways, only use them in the day, or forego public transportation altogether due to fear of victimization. According to Loukaitou-Sideris and Fink, much of this blame should be put into the lack of input women get when designing safety procedures for public transportation. Citing the lack of security, cameras, panic buttons, or other bystanders who could help, the authors argue that women will continue to avoid public transportation so long as there is no greater attempt to prevent crime around transportation infrastructure like bus stops, trains etc. If public transportation does in fact have a way of bringing crime to certain areas, increased security around transit stops could potentially help to mitigate this.


1. <a name="cite_note-1"></a> [^](#cite_ref-1) Phillips, David C., and Danielle Sandler. “Does Public Transit Spread Crime? Evidence from Temporary Rail Station Closures.” Regional Science and Urban Economics, vol. 52, 2015, pp. 13–26, https://doi.org/10.1016/j.regsciurbeco.2015.02.001
2. <a name="cite_note-2"></a> [^](#cite_ref-2)Ridgeway, Greg, and John M. MacDonald. Effect of Rail Transit on Crime: A Study of Los Angeles from 1988–2014. Department of Criminology Working Paper No. 2015-14.0, University of Pennsylvania, 2015, crim.sas.upenn.edu/sites/default/files/2015-14.0_Ridgeway_MacDonald_RailEffect%281%29.pdf.
3. <a name="cite_note-3"></a> [^](#cite_ref-3)Lewis, Tanya. “Is Public Transit Really Safer Than Driving?” Scientific American, 15 Apr. 2025, www.scientificamerican.com/article/is-public-transit-really-safer-than-driving/
4. <a name="cite_note-4"></a> [^](#cite_ref-4) Loukaitou-Sideris, Anastasia, and Camille Fink. “Addressing Women’s Fear of Victimization in Transportation Settings: A Survey of U.S. Transit Agencies.” Urban Affairs Review, vol. 44, no. 4, 2008, pp. 554–587, https://doi.org/10.1177/1078087408322874

## Hypothesis

We hypothesize that the relationship between San Diego Trolley ridership and nearby crime rates over time will be weak or mixed, rather than uniformly positive or negative. This is because we expect that any observed differences in crime patterns will be driven largely by preexisting neighborhood socioeconomic conditions, rather than the transit use itself. This aligns with prior research suggesting public transit is often blamed for crime patterns that reflect broader structural inequities rather than transit use.

Null Hypothesis: Changes in San Diego Trolley ridership have no association with nearby crime rates over time.

Alternative Hypothesis: Any association between trolley ridership and crime varies across neighborhoods and is more strongly related to socioeconomic context than to ridership levels alone.

### Setup

In [1]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback.

### Dataset #1 (use name instead of number here)

**NOTE** The final report should not be overly long.  If this wrangling step is huge and complicated you should remove these sections from the final report and replace them with a statement like "To see the code responsible for wrangling the data see `01-DataCheckpoint.ipynb`. From here on we will simply load the processed data for further analysis"

In [2]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Dataset #2: 2023-2025 San Diego Crime by Neighborhood Datasets
INSERT DESCRIPTION

Here, we will combine the datasets we cleaned from previous checkpoints.

In [3]:
crime_df_2023 = pd.read_csv('data/02-processed/clean_nibrs_crime_rates_2023.csv')
crime_df_2024 = pd.read_csv('data/02-processed/clean_nibrs_crime_rates_2024.csv')
crime_df_2025 = pd.read_csv('data/02-processed/clean_nibrs_crime_rates_2025.csv')

In [4]:
# Add a year column to all datasets
crime_df_2023['Year'] = [2023] * crime_df_2023.shape[0]
crime_df_2024['Year'] = [2024] * crime_df_2024.shape[0]
crime_df_2025['Year'] = [2025] * crime_df_2025.shape[0]

In [5]:
# Add all crime datasets together
crime_df = pd.concat([crime_df_2023, crime_df_2024, crime_df_2025])
crime_df

,Neighborhood,Homicide,Kidnapping/Abduction,Sexual Assault,Aggravated Assault,Simple Assault,Intimidation,Other Sex Offenses,Robbery,Arson,...,Fraud/Counterfeiting,Stolen Property Offenses,Vandalism,Drug/Narcotic Offenses,Pornography/Obscene Material,Gambling Offenses,Prostitution,Weapon Law Violations,Animal Cruelty,Year
0,ADAMS NORTH,0.0,0.00,0.00,1.50,3.00,0.30,0.00,0.50,0.00,...,1.50,0.30,4.70,1.70,0.00,0.0,0.00,0.30,0.2,2023
1,ALLIED GARDENS,0.0,0.10,0.10,1.10,2.60,0.10,0.00,0.00,0.10,...,1.30,0.80,2.60,1.10,0.00,0.0,0.00,0.30,0.0,2023
2,ALTA VISTA,0.0,0.00,0.00,1.10,3.30,0.40,0.00,0.00,0.00,...,0.70,0.00,1.90,0.40,0.00,0.0,0.00,0.00,0.0,2023
3,AZALEA/HOLLYWOOD PARK,0.0,0.00,0.60,3.00,7.30,0.30,0.30,0.90,0.30,...,3.00,1.50,4.00,3.40,0.00,0.3,0.00,2.40,0.0,2023
4,BALBOA PARK,0.0,4.30,14.90,51.20,89.60,10.70,0.00,19.20,2.10,...,2.10,6.40,74.60,89.60,0.00,0.0,0.00,2.10,0.0,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,TORREY PRESERVE,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,2025
121,UNIVERSITY CITY,0.0,0.04,0.33,0.81,2.22,0.28,0.04,0.55,0.02,...,2.11,0.12,2.36,0.70,0.02,0.0,0.00,0.05,0.0,2025
122,UNIVERSITY HEIGHTS,0.0,0.20,0.13,1.58,3.22,0.20,0.00,0.13,0.07,...,2.04,0.33,3.48,2.30,0.00,0.0,0.07,0.33,0.0,2025
123,VALENCIA PARK,0.0,0.00,0.53,4.68,5.11,1.06,0.00,0.32,0.00,...,1.17,0.21,3.30,1.60,0.00,0.0,0.00,0.53,0.0,2025
124,WOODED AREA,0.0,0.00,0.00,1.14,1.43,0.00,0.00,0.00,0.00,...,1.72,0.29,0.86,1.14,0.00,0.0,0.00,0.00,0.0,2025

In [6]:
# Now we can see how the crime rates changed in each neighborhood for each year
neighborhood_crime_df = crime_df.groupby(['Neighborhood', 'Year']).sum()
neighborhood_crime_df

                     Homicide  Kidnapping/Abduction  Sexual Assault  \
Neighborhood   Year
ADAMS NORTH    2023       0.0                  0.00            0.00
               2024       0.0                  0.20            0.20
               2025       0.0                  0.33            0.50
ALLIED GARDENS 2023       0.0                  0.10            0.10
               2024       0.0                  0.10            0.20
...                       ...                   ...             ...
VALENCIA PARK  2024       0.0                  0.00            0.40
               2025       0.0                  0.00            0.53
WOODED AREA    2023       0.0                  0.00            0.30
               2024       0.0                  0.00            0.00
               2025       0.0                  0.00            0.00

                     Aggravated Assault  Simple Assault  Intimidation  \
Neighborhood   Year
ADAMS NORTH    2023                1.50            3.00          0.30
               2024                1.20            2.30          0.00
               2025                0.66            1.49          0.00
ALLIED GARDENS 2023                1.10            2.60          0.10
               2024                1.20            2.30          0.40
...                                 ...             ...           ...
VALENCIA PARK  2024                5.60            6.70          0.60
               2025                4.68            5.11          1.06
WOODED AREA    2023                0.00            0.30          0.00
               2024                0.00            0.00          0.60
               2025                1.14            1.43          0.00

                     Other Sex Offenses  Robbery  Arson  \
Neighborhood   Year
ADAMS NORTH    2023                 0.0     0.50   0.00
               2024                 0.0     0.70   0.00
               2025                 0.0     0.33   0.17
ALLIED GARDENS 2023                 0.0     0.00   0.10
               2024                 0.0     0.30   0.00
...                                 ...      ...    ...
VALENCIA PARK  2024                 0.0     0.50   0.00
               2025                 0.0     0.32   0.00
WOODED AREA    2023                 0.0     0.00   0.00
               2024                 0.0     0.00   0.00
               2025                 0.0     0.00   0.00

                     Burglary/Breaking & Entering  ...  Motor Vehicle Theft  \
Neighborhood   Year                                ...
ADAMS NORTH    2023                          2.20  ...                 2.70
               2024                          1.20  ...                 2.70
               2025                          1.00  ...                 1.00
ALLIED GARDENS 2023                          1.20  ...                 2.00
               2024                          1.50  ...                 2.30
...                                           ...  ...                  ...
VALENCIA PARK  2024                          0.50  ...                 3.60
               2025                          0.96  ...                 1.49
WOODED AREA    2023                          0.30  ...                 1.40
               2024                          1.40  ...                 1.70
               2025                          0.57  ...                 0.57

                     Fraud/Counterfeiting  Stolen Property Offenses  \
Neighborhood   Year
ADAMS NORTH    2023                  1.50                      0.30
               2024                  1.30                      0.50
               2025                  1.99                      0.17
ALLIED GARDENS 2023                  1.30                      0.80
               2024                  1.50                      0.20
...                                   ...                       ...
VALENCIA PARK  2024                  1.40                      0.30
               2025                  1.17                      0.21
WOODED AREA    2023                  0.30                      0.00
               2024                  2.00                      0.30
               2025                  1.72                      0.29

                     Vandalism  Drug/Narcotic Offenses  \
Neighborhood   Year
ADAMS NORTH    2023       4.70                    1.70
               2024       3.70                    0.30
               2025       2.16                    0.83
ALLIED GARDENS 2023       2.60                    1.10
               2024       2.50                    1.40
...                        ...                     ...
VALENCIA PARK  2024       3.50                    2.90
               2025       3.30                    1.60
WOODED AREA    2023       1.70                    0.00
               2024       1.10                    1.10
               2025       0.86                    1.14

                     Pornography/Obscene Material  Gambling Offenses  \
Neighborhood   Year
ADAMS NORTH    2023                           0.0                0.0
               2024                           0.0                0.0
               2025                           0.0                0.0
ALLIED GARDENS 2023                           0.0                0.0
               2024                           0.0                0.0
...                                           ...                ...
VALENCIA PARK  2024                           0.0                0.0
               2025                           0.0                0.0
WOODED AREA    2023                           0.0                0.0
               2024                           0.0                0.0
               2025                           0.0                0.0

                     Prostitution  Weapon Law Violations  Animal Cruelty
Neighborhood   Year
ADAMS NORTH    2023           0.0                   0.30             0.2
               2024           0.0                   0.50             0.0
               2025           0.0                   0.50             0.0
ALLIED GARDENS 2023           0.0                   0.30             0.0
               2024           0.0                   0.40             0.0
...                           ...                    ...             ...
VALENCIA PARK  2024           0.0                   1.30             0.0
               2025           0.0                   0.53             0.0
WOODED AREA    2023           0.0                   0.00             0.0
               2024           0.0                   0.00             0.0
               2025           0.0                   0.00             0.0

[375 rows x 22 columns]

In [7]:
# Narrowing the datset to more prevalent, common crimes
selected_cols = [
    "Simple Assault",
    "Robbery",
    "Larceny",
    "Motor Vehicle Theft",
    "Vandalism",
    "Drug/Narcotic Offenses"
]

neighborhood_common_crime_df = neighborhood_crime_df[selected_cols]
neighborhood_common_crime_df

                     Simple Assault  Robbery  Larceny  Motor Vehicle Theft  \
Neighborhood   Year
ADAMS NORTH    2023            3.00     0.50     4.00                 2.70
               2024            2.30     0.70     5.20                 2.70
               2025            1.49     0.33     6.48                 1.00
ALLIED GARDENS 2023            2.60     0.00     2.00                 2.00
               2024            2.30     0.30     2.80                 2.30
...                             ...      ...      ...                  ...
VALENCIA PARK  2024            6.70     0.50     3.80                 3.60
               2025            5.11     0.32     3.09                 1.49
WOODED AREA    2023            0.30     0.00     2.00                 1.40
               2024            0.00     0.00     3.40                 1.70
               2025            1.43     0.00     4.29                 0.57

                     Vandalism  Drug/Narcotic Offenses
Neighborhood   Year
ADAMS NORTH    2023       4.70                    1.70
               2024       3.70                    0.30
               2025       2.16                    0.83
ALLIED GARDENS 2023       2.60                    1.10
               2024       2.50                    1.40
...                        ...                     ...
VALENCIA PARK  2024       3.50                    2.90
               2025       3.30                    1.60
WOODED AREA    2023       1.70                    0.00
               2024       1.10                    1.10
               2025       0.86                    1.14

[375 rows x 6 columns]

### Merging

In [25]:
clean_stops_df = pd.read_csv('data/02-processed/clean_transit_stops_datasd.csv')
clean_ridership_df = pd.read_csv('data/02-processed/cleaned_mts_trolley_ridership_data.csv')

In [26]:
def clean_stops(t):
    output = re.sub(r'[^\w\s]', ' ', t).lower().replace('station', '')
    output = re.sub(r'\bstreet\b|\bst\b', '', output, flags=re.IGNORECASE)
    output = re.sub(r'\bavenue\b|\bave\b', '', output, flags=re.IGNORECASE)
    return re.sub(r'\s+', ' ', output).strip()

In [27]:
clean_ridership_df['stop_join'] = clean_ridership_df['Station'].apply(clean_stops)

In [28]:
clean_stops_df['stop_join'] = np.where(
    (clean_stops_df['stop_id'].str[:2] == '75') | (clean_stops_df['stop_id'].str[:2] == '77'),
    clean_stops_df['stop_name'].apply(clean_stops), 
    np.nan
)
clean_stops_df['stop_join'] = clean_stops_df['stop_join'].str.replace('santee town center', 'santee').str.replace('union grantville', 'grantville')

In [32]:
clean_stops_df = clean_stops_df.groupby('stop_join').agg({'stop_lat': 'mean', 'stop_lon': 'mean', 'stop_id': 'first'}).reset_index()

In [35]:
clean_stops_df.merge(clean_ridership_df, on='stop_join').drop(columns=['stop_join'])

,stop_lat,stop_lon,stop_id,Station,Ridership,Season,Year,Neighborhood,Line
0,32.705828,-117.153272,75102,12th/Imperial,12936,Summer,2023,PETCO PARK,Blue
1,32.705828,-117.153272,75102,12th/Imperial,12936,Summer,2023,PETCO PARK,Green
2,32.705828,-117.153272,75102,12th/Imperial,12936,Summer,2023,PETCO PARK,Orange
3,32.705828,-117.153272,75102,12th/Imperial,13184,Fall,2023,PETCO PARK,Blue
4,32.705828,-117.153272,75102,12th/Imperial,13184,Fall,2023,PETCO PARK,Green
...,...,...,...,...,...,...,...,...,...
475,32.741633,-117.184379,75076,Washington St,1020,Summer,2024,MISSION HILLS,Green
476,32.741633,-117.184379,75076,Washington St,1013,Fall,2024,MISSION HILLS,Blue
477,32.741633,-117.184379,75076,Washington St,1013,Fall,2024,MISSION HILLS,Green
478,32.741633,-117.184379,75076,Washington St,1071,Spring,2025,MISSION HILLS,Blue
479,32.741633,-117.184379,75076,Washington St,1071,Spring,2025,MISSION HILLS,Green

In [36]:
neighborhood_common_crime_df

                     Simple Assault  Robbery  Larceny  Motor Vehicle Theft  \
Neighborhood   Year
ADAMS NORTH    2023            3.00     0.50     4.00                 2.70
               2024            2.30     0.70     5.20                 2.70
               2025            1.49     0.33     6.48                 1.00
ALLIED GARDENS 2023            2.60     0.00     2.00                 2.00
               2024            2.30     0.30     2.80                 2.30
...                             ...      ...      ...                  ...
VALENCIA PARK  2024            6.70     0.50     3.80                 3.60
               2025            5.11     0.32     3.09                 1.49
WOODED AREA    2023            0.30     0.00     2.00                 1.40
               2024            0.00     0.00     3.40                 1.70
               2025            1.43     0.00     4.29                 0.57

                     Vandalism  Drug/Narcotic Offenses
Neighborhood   Year
ADAMS NORTH    2023       4.70                    1.70
               2024       3.70                    0.30
               2025       2.16                    0.83
ALLIED GARDENS 2023       2.60                    1.10
               2024       2.50                    1.40
...                        ...                     ...
VALENCIA PARK  2024       3.50                    2.90
               2025       3.30                    1.60
WOODED AREA    2023       1.70                    0.00
               2024       1.10                    1.10
               2025       0.86                    1.14

[375 rows x 6 columns]

## Results

### Exploratory Data Analysis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your EDA feedback

**NOTE** The final report should not be overly long.  If this EDA step is huge and complicated  and you went down a lot of dead ends, then you should do something about that.  Some options... 

1) remove any EDA you later decided was unecessary side quest.
2) if the code to EDA is very long (in either lines or in time to compute) make sure you write out images of the EDA into `results/` and reload them as images here instead of recalculating it. And make a statement here like "To see the code responsible for EDA analyses see `02-EDACheckpoint.ipynb`."

### First Analysis You Did - Give it a better title

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.  Every project will be different here... but some examples of analyses are: inferential statistics where you calculate p-values (like a t-test or a Monte Carlo simulation), regression models, or a machine learning model

**NOTE** The final report should not be overly long.  If this analysis step is huge and complicated  and you went down a lot of dead ends, then you should do something about that.  Some options... 

1) remove any analysis you later decided was unecessary side quest before checking in for the final hand in
2) if the code to do an analysis is very long (in either lines or in time to compute) put it in a different file.  In that file make write out results of analysis into `results/` and reload the results here instead of recalculating it. And make a statement here like "To see the code responsible for analyses see `path/to/some-file-name.ipynb_or.py`."

In [9]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Second Analysis You Did - Give it a better title

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.  Every project will be different here... but some examples of analyses are: inferential statistics where you calculate p-values (like a t-test or a Monte Carlo simulation), regression models, or a machine learning model

In [10]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### ETC AD NASEUM

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [11]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Discusison and Conclusion

Wrap it all up here.  Somewhere between 3 and 10 paragraphs roughly. 
1. Summarize the important results you made
2. This is a good time to refer back to your Background section and review how this work extended the previous stuff.
3. Try to bring all the different results together into a bigger picture... what have we learned?
4. Often what we learned is confusing.  Discuss if there are contradictory results how that might have happened
5. Discuss the limitations of your work. e.g, is the dataset a biased sample? would more data make you more confident? would longitudinal instead of cross-sectional data helpful? is there evidence that the phenomena you're investigating may change over time? etc
6. If you would like, you can also say what the next steps in this investigation might be if the work was to continue outside this class